language: node_js
node_js:
  - "8"
script:
  - git checkout package-lock.json
  - npm run build
  - npm run lint
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  except:
    - release
