language: node_js
node_js:
  - "4.1"
before_script:
  - npm install -g gulp
  - npm install -g typescript@next
script:
  - tsc
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
